@startuml
'https://plantuml.com/sequence-diagram

class TodoList {
    todoLists: List<List>
    directory: String

    setDirectory()
    createDirectory()
    addNewList()
    deleteList()
    editListTitle()
    saveAllExternally()
    loadList()
}

class TodoListController {
    loadButtonClicked()
    newListButtonClicked()
    saveListsButtonClicked()
    openListButtonClicked
}

class ListViewController {
    initialize()
    initTable()
    initCols()
    editableCols()
    loadData()
    loadNewData()
    setTitle()
    itemAdded()
    backButtonClicked()
    deleteItemButtonClicked()
    deleteListButtonClicked()
    listTitleEdited()
    loadComplete()
    loadIncomplete()
    showCompleteButtonClicked()
    showIncompleteButtonClicked()
    showAllButtonClicked()
    markedComplete()
    markedIncomplete()
    saveListButtonClicked()
}

class ListViewOpenController {
    selectedList: List

    initialize()
    initTable()
    initCols()
    editableCols()
    loadData()
    itemAdded()
    backButtonClicked()
    deleteItemButtonClicked()
    deleteListButtonClicked()
    listTitleEdited()
    loadComplete()
    loadIncomplete()
    showCompleteButtonClicked()
    showIncompleteButtonClicked()
    showAllButtonClicked()
    markedComplete()
    markedIncomplete()
    saveListButtonClicked()
}

class MainClass {
 main()
 start()
}

class List {
    title: String
    itemList: List<Item>
    directory: String

    List()
    getTitle()
    setTitle()
    setDirectory()
    createDirectory()
    addNewItem()
    deleteItem()
    editDescription()
    editDueDate()
    editStatus()
    saveItemsExternally()
}

class Item {
    description: String
    dueDate: String
    status: String

    Item()
    setDescription()
    getDescription()
    setDueDate()
    getDueDate()
    getStatus()
    markComplete()
    markIncomplete()
}

javafx.Application <|-- MainClass
MainClass <|-- TodoList
TodoList -- List
TodoList -- TodoListController
TodoList -- ListViewController
TodoList -- ListViewOpenController
List - Item

@enduml